/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../views/element/basic/Button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./../views/zero/HelloWorld.vue')['default']
    Overview: typeof import('./../views/element/basic/Overview.vue')['default']
    README: typeof import('./../views/element/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Unocss: typeof import('./../plugins/unocss/index.ts')['default']
  }
}
